layout_spectrum: 0.4507287
typography_spectrum: 0.2013803
color:
  saturation: 0.7958818
  lightness: 0.7357088
  brandStrength: 0.06338608
  rhythmicContrast: 0.640444
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Stieger
